### ISSUE TITLE
Fix `CanCheckForInnoSetupReleases` on macOS

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1042]
https://github.com/Nexus-Mods/NexusMods.App/actions/runs/8186152842?pr=1034

**CanCheckForInnoSetupReleases**

```
Expected (ConcreteVm.ShouldShow()) to be true, but found False.
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeTrue(String because, Object[] becauseArgs)
   at NexusMods.UI.Tests.Overlays.UpdaterViewModelTests.CanCheckForInnoSetupReleases() in /Users/runner/work/NexusMods.App/NexusMods.App/tests/NexusMods.UI.Tests/Overlays/UpdaterViewModelTests.cs:line 39
```

https://github.com/Nexus-Mods/NexusMods.App/actions/runs/8246474841/attempts/1

**CanCheckForInnoSetupReleases**

```
Expected (ConcreteVm.ShouldShow()) to be true, but found False.
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeTrue(String because, Object[] becauseArgs)
   at NexusMods.UI.Tests.Overlays.UpdaterViewModelTests.CanCheckForInnoSetupReleases() in /Users/runner/work/NexusMods.App/NexusMods.App/tests/NexusMods.UI.Tests/Overlays/UpdaterViewModelTests.cs:line 39
```

**Comment by erri120** [comment]
@halgari it appears that the `UpdaterViewModelTests` are breaking, most likely because they contact GitHub and ask for a release. None of the logging statements are actually outputted to the test log, so we can't be sure what's failing.

**Comment by erri120** [comment]
![2024-03-13_10-28-43](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/d5735e37-a81f-447c-b14a-546055e76f2f)

https://github.com/Nexus-Mods/NexusMods.App/actions/runs/8261961024?pr=1057

This one is on macos-latest, still the same method.
