### ISSUE TITLE
Sorted loadout grid throws an exception when deleting a mod

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1097]
How to reproduce:

1) Install some mods
2) Sort the grid by some column (eg Name)
3) Select and delete a mod

```
System.Collections.Generic.KeyNotFoundException: The given key '0e473914-71e4-4152-a4a5-f1a74e9241dc' was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at NexusMods.Abstractions.Serialization.DataModel.EntityDictionary`2.get_Item(TK k) in /ssd-pool/projects/NexusMods/app/main/src/Abstractions/NexusMods.Abstractions.Serialization/DataModel/EntityDictionary.cs:line 62
   at NexusMods.DataModel.Loadouts.LoadoutRegistry.Get(LoadoutId loadoutId, ModId modId) in /ssd-pool/projects/NexusMods/app/main/src/NexusMods.DataModel/Loadouts/LoadoutRegistry.cs:line 292
   at NexusMods.DataModel.Loadouts.LoadoutRegistry.Get(ModCursor cursor) in /ssd-pool/projects/NexusMods/app/main/src/NexusMods.DataModel/Loadouts/LoadoutRegistry.cs:line 269
   at NexusMods.App.UI.Pages.LoadoutGrid.Columns.ModName.ModNameViewModel.Compare(ModCursor a, ModCursor b) in /ssd-pool/projects/NexusMods/app/main/src/NexusMods.App.UI/Pages/LoadoutGrid/Columns/ModName/ModNameViewModel.cs:line 40
   at NexusMods.App.UI.Controls.DataGrid.DataGridViewModelColumn`2.<>c__DisplayClass3_0.<CreateComparer>b__1(Object a, Object b) in /ssd-pool/projects/NexusMods/app/main/src/NexusMods.App.UI/Controls/DataGrid/DataGridViewModelColumn.cs:line 37
   at Avalonia.Collections.DataGridComparerSortDescription.Compare(Object x, Object y)
   at Avalonia.Collections.DataGridComparerSortDescription.<.ctor>b__9_0(Object x, Object y)
   at Avalonia.Collections.DataGridCollectionView.MergedComparer.Compare(Object x, Object y)
   at Avalonia.Collections.DataGridCollectionView.MergedComparer.FindInsertIndex(Object x, IList list)
   at Avalonia.Collections.DataGridCollectionView.ProcessInsertToCollection(Object item, Int32 index)
   at Avalonia.Collections.DataGridCollectionView.ProcessAddEvent(Object addedItem, Int32 addIndex)
   at Avalonia.Collections.DataGridCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at Avalonia.Collections.DataGridCollectionView.<.ctor>b__27_0(Object _, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ReadOnlyObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ReadOnlyObservableCollection`1.HandleCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at DynamicData.Binding.ObservableCollectionExtended`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e) in /_/src/DynamicData/Binding/ObservableCollectionExtended.cs:line 158
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedAction action, Object oldItem, Object newItem, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1.SetItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.set_Item(Int32 index, T value)
   at DynamicData.ListEx.Replace[T](IList`1 source, T original, T replaceWith) in /_/src/DynamicData/List/ListEx.cs:line 381
   at DynamicData.Binding.ObservableCollectionAdaptor`2.DoUpdate(IChangeSet`2 changes, IObservableCollection`1 list) in /_/src/DynamicData/Binding/ObservableCollectionAdaptor.cs:line 154
   at DynamicData.Binding.ObservableCollectionAdaptor`2.Adapt(IChangeSet`2 changes, IObservableCollection`1 collection) in /_/src/DynamicData/Binding/ObservableCollectionAdaptor.cs:line 130
   at DynamicData.ObservableCacheEx.<>c__DisplayClass28_0`2.<Bind>b__1(IChangeSet`2 changes) in /_/src/DynamicData/Cache/ObservableCacheEx.cs:line 580
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
```

**Comment by Pickysaurus** [comment]
Tested this in 0.5.2 and could not replicate it.

**Comment by LukeNexusMods** [comment]
Is this now fixed?
