### ISSUE TITLE
Exception when indexing Stardew Valley installed with Xbox Game Pass

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1476]
```log
00:00:25.295 [ERROR] (NexusMods.App.Program) Encountered an exception published to an object with an unobserved ThrownExceptions property|System.UnauthorizedAccessException: Access to the path 'C:\Games\Xbox\Stardew Valley\Content\createdump.exe' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at NexusMods.Paths.FileSystem.InternalCreateMemoryMappedFile(AbsolutePath absPath, FileMode mode, MemoryMappedFileAccess access)
   at NexusMods.Paths.BaseFileSystem.CreateMemoryMappedFile(AbsolutePath absPath, FileMode mode, MemoryMappedFileAccess access)
   at NexusMods.Extensions.Hashing.AbsolutePathExtensions.XxHash64MemoryMapped(AbsolutePath input, IActivitySource`1 job) in C:\Projects\NexusMods.App\src\Extensions\NexusMods.Extensions.Hashing\AbsolutePathExtensions.cs:line 44
   at NexusMods.DataModel.FileHashCache.<>c__DisplayClass7_0.<IndexFoldersAsync>b__4(IFileEntry info, CancellationToken _) in C:\Projects\NexusMods.App\src\NexusMods.DataModel\FileHashCache.cs:line 103
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at NexusMods.DataModel.FileHashCache.IndexFoldersAsync(IEnumerable`1 paths, CancellationToken token)+MoveNext() in C:\Projects\NexusMods.App\src\NexusMods.DataModel\FileHashCache.cs:line 92
   at NexusMods.DataModel.FileHashCache.IndexFoldersAsync(IEnumerable`1 paths, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at NexusMods.DataModel.FileHashCache.IndexDiskState(GameInstallation installation) in C:\Projects\NexusMods.App\src\NexusMods.DataModel\FileHashCache.cs:line 142
   at NexusMods.Abstractions.Loadouts.Synchronizers.ALoadoutSynchronizer.GetOrCreateInitialDiskState(GameInstallation installation) in C:\Projects\NexusMods.App\src\Abstractions\NexusMods.Abstractions.Loadouts.Synchronizers\ALoadoutSynchronizer.cs:line 1212
   at NexusMods.Abstractions.Loadouts.Synchronizers.ALoadoutSynchronizer.CreateLoadout(GameInstallation installation, String suggestedName) in C:\Projects\NexusMods.App\src\Abstractions\NexusMods.Abstractions.Loadouts.Synchronizers\ALoadoutSynchronizer.cs:line 922
   at NexusMods.App.UI.Pages.MyGames.MyGamesViewModel.ManageGame(GameInstallation installation) in C:\Projects\NexusMods.App\src\NexusMods.App.UI\Pages\MyGames\MyGamesViewModel.cs:line 129
   at NexusMods.App.UI.Pages.MyGames.MyGamesViewModel.<>c__DisplayClass7_3.<<-ctor>b__11>d.MoveNext() in C:\Projects\NexusMods.App\src\NexusMods.App.UI\Pages\MyGames\MyGamesViewModel.cs:line 99
--- End of stack trace from previous location ---
   at NexusMods.App.UI.Pages.MyGames.MyGamesViewModel.<>c__DisplayClass7_3.<<-ctor>b__9>d.MoveNext() in C:\Projects\NexusMods.App\src\NexusMods.App.UI\Pages\MyGames\MyGamesViewModel.cs:line 99

```

**Comment by Al12rs** [comment]
https://stardewvalleywiki.com/Modding:Installing_SMAPI_on_Windows#Xbox_app
