### ISSUE TITLE
Clicking apply to apply stardew valley mods, mod app gives error and play button remains grayed out

### ISSUE THREAD

**Issue by ConnorMartin138** [Nexus-Mods/NexusMods.App#1628]
# Bug Report

## Summary
When clicking apply to apply any Stardew Valley mods, in this instance just SMAPI, the console gives the error message given below, and the play button remains grayed out.

## Steps to reproduce
Completely uninstalled and reinstalled Stardew and Mod App, reinstalled Stardew and Mod App from fresh downloads. Opened Mod App, all mods still in library, set only SMAPI to active, click apply.

## What is the expected behaviour?
Should apply mods and allow play button to work.

## Other information
Running linux. I completely removed stardew valley and mod app and removed all the config or save locations I could find for both and when I reinstalled the game and mod app again it remains the same.

Console output:

00:01:55.763 [ERROR] Encountered an exception published to an object with an unobserved ThrownExceptions property|System.NullReferenceException: Object reference not set to an instance of an object.

   at NexusMods.Abstractions.Loadouts.Synchronizers.ALoadoutSynchronizer.FindChangedFiles(DiskStateTree diskState, Model loadout, FileTree prevFileTree, DiskStateTree prevDiskState) in /_/src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs:line 647

   at NexusMods.Abstractions.Loadouts.Synchronizers.ALoadoutSynchronizer.Ingest(Model loadout) in /_/src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs:line 582

   at NexusMods.DataModel.ApplyService.Apply(Model loadout) in /_/src/NexusMods.DataModel/ApplyService.cs:line 66

   at NexusMods.App.UI.LeftMenu.Items.ApplyControlViewModel.<Apply>b__39_0() in /_/src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:line 158

   at NexusMods.App.UI.LeftMenu.Items.ApplyControlViewModel.Apply() in /_/src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:line 155

   at NexusMods.App.UI.LeftMenu.Items.ApplyControlViewModel.<>c__DisplayClass38_0.<<-ctor>b__0>d.MoveNext() in /_/src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:line 57

Log Files:
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/15857168/nexusmods.app.main.current.log)
[nexusmods.app.slim.current.log](https://github.com/user-attachments/files/15857169/nexusmods.app.slim.current.log)

**Comment by erri120** [comment]
0.5.1:

https://github.com/Nexus-Mods/NexusMods.App/blob/98fd59841040da98eed91198653045bb890e7642/src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs#L647

main:

https://github.com/Nexus-Mods/NexusMods.App/blob/595937917de44c135294b3ab39d6f50905d7f4b4/src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs#L647

We're using `!` to circumvent the null-check. No idea why we're doing this, but we shouldn't do that as seen here. @Sewer56 I think you wrote this.

**Comment by Al12rs** [comment]
This problem is very likely this:
- #1473

**Comment by Sewer56** [comment]
> We're using ! to circumvent the null-check. No idea why we're doing this, but we shouldn't do that as seen here. @Sewer56 I think you wrote this.

Would have been @halgari , I've never really worked on that part of the Synchronizer.
Last time this would have been changed would have been during migration to MnemonicDB.

IIRC the whole method `FindChangedFiles` was lifted out of Ingest.
I think @Al12rs 's on the money, with it being related to #1473

**Comment by Al12rs** [comment]
The assumption in question is that we can find the matching LoadoutFile entry in the current loadout of something that was in the Old DiskState.
Before the passed loadout for this operation was the LastAppliedRevision loaodut revision, not the current loadout revision.
