### ISSUE TITLE
Cannot run new version 0.5.3 on Fedora 40.; immediate crash.

### ISSUE THREAD

**Issue by JooJooBee666** [Nexus-Mods/NexusMods.App#1871]
# Bug Report

## Summary
The app just doesn't load.  0.5.2 worked fine but the 0.5.3 AppImage does not.  
```
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more hosted services failed to start. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.))
 ---> System.AggregateException: One or more hosted services failed to start. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NexusMods.StandardGameLocators.ManuallyAddedGame.FindByGameDomain(IDb db, GameDomain value) in /_/src/NexusMods.StandardGameLocators/obj/Release/net8.0/NexusMods.MnemonicDB.SourceGenerator/NexusMods.MnemonicDB.SourceGenerator.ModelGenerator/NexusMods_StandardGameLocators_ManuallyAddedGame.Generated.cs:line 39
   at NexusMods.StandardGameLocators.ManuallyAddedLocator.Find(ILocatableGame game) in /_/src/NexusMods.StandardGameLocators/ManuallyAddedLocator.cs:line 73
   at NexusMods.DataModel.GameRegistry.FindInstallations()+MoveNext() in /_/src/NexusMods.DataModel/GameRegistry/GameRegistry.cs:line 136
   at System.Collections.Generic.AsyncEnumerableHelpers.ToSet[T](IAsyncEnumerable`1 source, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerableHelpers.cs:line 108
   at System.Collections.Generic.AsyncEnumerableHelpers.ToSet[T](IAsyncEnumerable`1 source, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerableHelpers.cs:line 108
   at System.Linq.AsyncEnumerable.DistinctAsyncIterator`1.ToArrayAsync(CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Distinct.cs:line 56
   at NexusMods.DataModel.GameRegistry.Startup(CancellationToken token) in /_/src/NexusMods.DataModel/GameRegistry/GameRegistry.cs:line 69
   at NexusMods.DataModel.GameRegistry.StartAsync(CancellationToken cancellationToken) in /_/src/NexusMods.DataModel/GameRegistry/GameRegistry.cs:line 151
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0&)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
 ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at NexusMods.Networking.Downloaders.Tasks.State.DownloaderState.All(IDb db) in /_/src/Networking/NexusMods.Networking.Downloaders/obj/Release/net8.0/NexusMods.MnemonicDB.SourceGenerator/NexusMods.MnemonicDB.SourceGenerator.ModelGenerator/NexusMods_Networking_Downloaders_Tasks_State_DownloaderState.Generated.cs:line 81
   at NexusMods.Networking.Downloaders.DownloadService.StartAsync(CancellationToken cancellationToken) in /_/src/Networking/NexusMods.Networking.Downloaders/DownloadService.cs:line 162
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)<---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
   at NexusMods.App.Program.Main(String[] args) in /_/src/NexusMods.App/Program.cs:line 63
Aborted (core dumped)
```

## Steps to reproduce
Download 0.5.3 AppImage and try running it!

## What is the expected behaviour?
I expect it to **open**, lol/

## Other information
See above.

[nexusmods.app.main.current.log](https://github.com/user-attachments/files/16581373/nexusmods.app.main.current.log)
[nexusmods.app.slim.current.log](https://github.com/user-attachments/files/16581382/nexusmods.app.slim.current.log)

**Comment by JooJooBee666** [comment]
Confirmed.  Thanks.  Didn't see find the previous report.
