### ISSUE TITLE
App crashes after loading "Winter in Night City"

### ISSUE THREAD

**Issue by duckythescientist** [Nexus-Mods/NexusMods.App#1933]
# Bug Report

## Summary

After loading in the [Winter in Night City](https://www.nexusmods.com/cyberpunk2077/mods/11894) mod, the NexusMods.App crashes when trying to view the game.

## Steps to reproduce

From a fresh install of the App with Cyberpunk already installed on the system:

Download [Winter in Night City](https://www.nexusmods.com/cyberpunk2077/mods/11894) and add the archive.

Wait a few seconds for the 3GB archive file to get parsed and show up in the mod list.

Click the "Add" button. 

Click the "Apply" button. Note: the apply doesn't seem to work. 

```
00:00:27.587 [DEBUG] Extracting 3 files to disk
00:00:27.682 [ERROR] Encountered an exception published to an object with an unobserved ThrownExceptions property|System.ArgumentException: A positive capacity must be specified for a Memory Mapped File backed by an empty file.
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(String path, FileMode mode, String mapName, Int64 capacity, MemoryMappedFileAccess access)
   at NexusMods.Archives.Nx.FileProviders.OutputFileProvider..ctor(String outputFolder, String relativePath, FileEntry entry)
   at NexusMods.DataModel.NxFileStore.<>c__DisplayClass7_1.<ExtractFiles>b__2(Int32 x) in /_/src/NexusMods.DataModel/NxFileStore.cs:line 182
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

Close the NexusMods.App.

Reopen the NexusMods.App.

Click the "View" button on Cyberpunk.

The NexusMods.App crashes.

```
00:00:05.368 [ERROR] Encountered an unobserved task exception in the Task Scheduler from sender of type `System.Threading.Tasks.UnwrapPromise`1[System.Threading.Tasks.VoidTaskResult]`: `System.Threading.Tasks.UnwrapPromise`1[System.Threading.Tasks.VoidTaskResult]`|System.ArgumentException: A positive capacity must be specified for a Memory Mapped File backed by an empty file.
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(String path, FileMode mode, String mapName, Int64 capacity, MemoryMappedFileAccess access)
   at NexusMods.Archives.Nx.FileProviders.OutputFileProvider..ctor(String outputFolder, String relativePath, FileEntry entry)
   at NexusMods.DataModel.NxFileStore.<>c__DisplayClass7_1.<ExtractFiles>b__2(Int32 x) in /_/src/NexusMods.DataModel/NxFileStore.cs:line 182
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at NexusMods.Archives.Nx.FileProviders.OutputFileProvider.Dispose()
   at NexusMods.Archives.Nx.FileProviders.OutputFileProvider.Finalize()
Aborted (core dumped)
```

I also haven't figured out a way to recover from this other than doing the `uninstall-app` action. 

## Other information

Ubuntu 23.04

[nexusmods.app.main.current.log](https://github.com/user-attachments/files/16741634/nexusmods.app.main.current.log)
[nexusmods.app.slim.current.log](https://github.com/user-attachments/files/16741635/nexusmods.app.slim.current.log)

**Comment by Sewer56** [comment]
I legitimately thought I fixed this edge case.
No matter, I'll handle it next week.

**Comment by Nebula-0-System** [comment]
i would like to add on that i also get this error recurrently as well when attempting to view loaded mods for cyberpunk 2077 on Linux Mint virginia 21.3 x86_64. i have multiple loaded, and it happens anytime i try to even view the mods i have installed.

just confirming i am also able to reproduce, and in an identical use case, i'm just unsure which mod is causing the problem because, well, the crash happens before i can modify the ones i am trying to apply.

**Comment by Nebula-0-System** [comment]
> Ah, we skipped release last sprint. So 0.5.3 is almost 2 months old.
> 
> Turns out I was on the money earlier, _I did already fix this_. Please wait for 0.6.0

fantastic, i'm excited! thanks : )
