### ISSUE TITLE
CI Test Failure: `CanCreateAndManageLists`: "Failed to store the file" 

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1969]
https://github.com/Nexus-Mods/NexusMods.App/actions/runs/10670396662/job/29574319637?pr=1967

```
[xUnit.net 00:00:00.95]     NexusMods.CLI.Tests.VerbTests.ModManagementVerbs.CanCreateAndManageLists [FAIL]
[xUnit.net 00:00:00.95]       System.Exception : Failed to store the file
[xUnit.net 00:00:00.95]       Stack Trace:
[xUnit.net 00:00:00.95]         /_/src/NexusMods.DataModel/CommandLine/Verbs/LoadoutManagementVerbs.cs(102,0): at NexusMods.DataModel.CommandLine.Verbs.LoadoutManagementVerbs.<>c__DisplayClass4_0.<<InstallMod>b__0>d.MoveNext()
[xUnit.net 00:00:00.95]         --- End of stack trace from previous location ---
[xUnit.net 00:00:00.95]         /_/src/NexusMods.DataModel/CommandLine/Verbs/LoadoutManagementVerbs.cs(110,0): at NexusMods.DataModel.CommandLine.Verbs.LoadoutManagementVerbs.<>c__DisplayClass4_0.<<InstallMod>b__0>d.MoveNext()
[xUnit.net 00:00:00.95]         --- End of stack trace from previous location ---
[xUnit.net 00:00:00.95]         /_/src/Abstractions/NexusMods.Abstractions.Cli/RendererExtensions.cs(55,0): at NexusMods.Abstractions.Cli.RendererExtensions.WithProgress[T](IRenderer renderer, CancellationToken token, Func`1 fn)
[xUnit.net 00:00:00.95]         /_/src/NexusMods.DataModel/CommandLine/Verbs/LoadoutManagementVerbs.cs(94,0): at NexusMods.DataModel.CommandLine.Verbs.LoadoutManagementVerbs.InstallMod(IRenderer renderer, ReadOnly loadout, AbsolutePath file, String name, ILibraryService libraryService, CancellationToken token)
[xUnit.net 00:00:00.95]            at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
[xUnit.net 00:00:00.95]         --- End of stack trace from previous location ---
[xUnit.net 00:00:00.95]            at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
[xUnit.net 00:00:00.95]         --- End of stack trace from previous location ---
[xUnit.net 00:00:00.95]            at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
[xUnit.net 00:00:00.95]         --- End of stack trace from previous location ---
[xUnit.net 00:00:00.95]            at System.CommandLine.Invocation.InvocationPipeline.<InvokeAsync>g__FullInvocationChainAsync|2_0(InvocationContext context)
[xUnit.net 00:00:00.95]            at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
[xUnit.net 00:00:00.95]            at System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console)
[xUnit.net 00:00:00.95]         /_/src/NexusMods.SingleProcess/CommandLineConfigurator.cs(158,0): at NexusMods.SingleProcess.CommandLineConfigurator.RunAsync(String[] args, IRenderer renderer, CancellationToken token)
[xUnit.net 00:00:00.95]         D:\a\NexusMods.App\NexusMods.App\tests\NexusMods.CLI.Tests\VerbTests\AVerbTest.cs(37,0): at NexusMods.CLI.Tests.VerbTests.AVerbTest.Run(String[] args)
[xUnit.net 00:00:00.95]         D:\a\NexusMods.App\NexusMods.App\tests\NexusMods.CLI.Tests\VerbTests\ModManagementVerbs.cs(28,0): at NexusMods.CLI.Tests.VerbTests.ModManagementVerbs.CanCreateAndManageLists()
[xUnit.net 00:00:00.95]       Output:
[xUnit.net 00:00:00.95]         [2024-09-02 16:21:50Z] dbug: NexusMods.FileExtractor.Extractors.SevenZipExtractor[0]
[xUnit.net 00:00:00.95]               Extracting StubbedGameState.zip
```

Might be a problem with concurrent access to `StubbedGameState.zip` but this is pure conjecture.
Test passes fine locally.

**Comment by LukeNexusMods** [comment]
Flaky test - problem with file in use.
