### ISSUE TITLE
Linux login failures

### ISSUE THREAD

**Issue by aakropotkin** [Nexus-Mods/NexusMods.App#1979]
I've been unable to login using v0.4.1 ( not sure if this issue has been fixed since then ).

When clicking "Log In" in the app it successfully launched my browser, and I can see in logs that it's catching the `nxm://...` handler; but ultimately I get a `Command result: 1`.

I was able to get a back-trace by using `NexusMods.app nexus-login` which looks like this:

```
$ NexusMods.app nexus-login
...<SNIP>...
00:06:04.309 [ERROR] Unable to login: task was canceled|System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NexusMods.Networking.NexusWebApi.Auth.OAuth.AuthorizeToken(String verifier, String code, CancellationToken cancel) in /build/source/src/Networking/NexusMods.Networking.NexusWebApi/Auth/OAuth.cs:line 137
   at NexusMods.Networking.NexusWebApi.Auth.OAuth.AuthorizeRequest(CancellationToken cancellationToken) in /build/source/src/Networking/NexusMods.Networking.NexusWebApi/Auth/OAuth.cs:line 95
   at NexusMods.Networking.NexusWebApi.LoginManager.LoginAsync(CancellationToken token) in /build/source/src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs:line 109
```

**Comment by erri120** [comment]
> I've been unable to login using v0.4.1 ( not sure if this issue has been fixed since then ).

Please try the latest version.
