### ISSUE TITLE
Exception when deleting an item from the library

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1994]
```
System.Collections.Generic.KeyNotFoundException: Entity EId:20000000000077C does not have attribute NexusMods.DataModel.ArchivedFile/Container
   at NexusMods.MnemonicDB.Abstractions.Attributes.ScalarAttribute`2.ThrowKeyNotfoundException(IHasEntityIdAndDb entity)
   at NexusMods.MnemonicDB.Abstractions.Attributes.ScalarAttribute`2.Get(IHasIdAndIndexSegment entity)
   at NexusMods.Abstractions.FileStore.Nx.Models.ArchivedFile.ReadOnly.get_Container() in /mnt/redline/projects/NexusMods/app/main/src/Abstractions/NexusMods.Abstractions.FileStore.Nx/obj/Debug/net8.0/NexusMods.MnemonicDB.SourceGenerator/NexusMods.MnemonicDB.SourceGenerator.ModelGenerator/NexusMods_Abstractions_FileStore_Nx_Models_ArchivedFile.Generated.cs:line 297
   at NexusMods.App.GarbageCollection.DataModel.NxFileStoreUpdater.UpdateNxFileStore(List`1 toRetract, AbsolutePath newArchivePath) in /mnt/redline/projects/NexusMods/app/main/src/NexusMods.App.GarbageCollection.DataModel/NxFileStoreUpdater.cs:line 44
   at NexusMods.App.GarbageCollection.DataModel.RunGarbageCollector.<>c__DisplayClass0_0.<Do>b__0(IProgress`1 progress, List`1 toArchive, List`1 toRemove, ArchiveReference`1 archive) in /mnt/redline/projects/NexusMods/app/main/src/NexusMods.App.GarbageCollection.DataModel/RunGarbageCollector.cs:line 27
   at NexusMods.App.GarbageCollection.ArchiveGarbageCollector`2.CollectGarbage(IProgress`1 progress, RepackDelegate doRepack) in /mnt/redline/projects/NexusMods/app/main/src/NexusMods.App.GarbageCollection/ArchiveGarbageCollector.cs:line 133
   at NexusMods.App.GarbageCollection.DataModel.RunGarbageCollector.Do(Span`1 archiveLocations, IFileStore store, IConnection connection) in /mnt/redline/projects/NexusMods/app/main/src/NexusMods.App.GarbageCollection.DataModel/RunGarbageCollector.cs:line 24
   at NexusMods.DataModel.GarbageCollectorRunner.Run() in /mnt/redline/projects/NexusMods/app/main/src/NexusMods.DataModel/GarbageCollectorRunner.cs:line 17
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```
### Edit:
From @Sewer56 

##### Reproduction

To understand the dangers involved, let's try reproducing the bug.

!!! note "The bug is fixed today."

    Today, the 'bug' is fixed as of commit ( `34de799623cf9688e6c3dcabca7fe029426583ed` ) , however prior to it;
    the bug could be reproduced in the way listed below.

We will make an assumption that we have an un-patched GC and faulty code that
creates duplicates.

Create 2 archives:

- dummy-1 (zip)
- dummy-2 (zip)

Inside `dummy-1`, add 1 file.
Inside `dummy-2`, add the file from `dummy-1`, and an additional file.

Add the `dummy-1` and `dummy-2` archives from disk in the following order:

- dummy-1
- dummy-2

Adding `dummy-2` creates a duplicate file due to an error by the programmer,
the `DataStore` entry for the duplicate hash will be re-routed to `dummy-2` when
it previously pointed to `dummy-1`.

If we now delete `dummy-1`; the error should have a 50-50 chance of reproducing;
depending on order archives are processed. There is a risk retracting the item in the
DataStore will retract the item in the wrong archive/container.

!!! note "There is some RNG involved."

    Reproduction is non-determinstic, due to nature of data.
    Bigger archives with duplicates are more likely to yield errors.

    So you can replace `dummy-1` with `SMAPI 4` and `dummy-2` with `SMAPI 3` 
    for a more reliable reproduction.

**Comment by Al12rs** [comment]
Discord conversation with @Sewer56 about this issue:
https://discord.com/channels/1134149061080002713/1134151856537469060/1281193806976516106

**Comment by Al12rs** [comment]
Fix was reverted
