### ISSUE TITLE
Unable to deserialize collection JSON

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#2020]
Tested with https://next.nexusmods.com/stardewvalley/collections/tckf0m

```
00:05:07.781 [ERROR] Exception while running handler NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler for `nxm://stardewvalley/collections/tckf0m/revisions/72`|System.Text.Json.JsonException: The JSON value could not be converted to NexusMods.Abstractions.Collections.Json.ModSourceType. Path: $.mods[8].source.type | LineNumber: 196 | BytePositionInLine: 24.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.ReadEnumUsingNamingPolicy(String enumString)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at NexusMods.Collections.InstallCollectionJob.StartAsync(IJobContext`1 context) in /mnt/redline/projects/NexusMods/app/main/src/NexusMods.Collections/InstallCollectionJob.cs:line 72
   at NexusMods.Collections.InstallCollectionJob.StartAsync(IJobContext`1 context) in /mnt/redline/projects/NexusMods/app/main/src/NexusMods.Collections/InstallCollectionJob.cs:line 72
   at NexusMods.Jobs.JobContext`2.Start() in /mnt/redline/projects/NexusMods/app/main/src/NexusMods.Jobs/JobContext.cs:line 43
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.HandleCollectionUrl(NXMCollectionUrl collectionUrl) in /mnt/redline/projects/NexusMods/app/main/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 120
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.HandleCollectionUrl(NXMCollectionUrl collectionUrl) in /mnt/redline/projects/NexusMods/app/main/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 120
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.Handle(String url, CancellationToken cancel) in /mnt/redline/projects/NexusMods/app/main/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 82
   at NexusMods.SingleProcess.CommandLineConfigurator.RunLink(String[] args, CancellationToken cancellationToken) in /mnt/redline/projects/NexusMods/app/main/src/NexusMods.SingleProcess/CommandLineConfigurator.cs:line 119

```

**Comment by erri120** [comment]
The part that caused the exception:

```json
{
    {
      "name": "UI Info Suite 2",
      "version": "2.3.3",
      "optional": false,
      "domainName": "stardewvalley",
      "source": {
        "type": "browse",
        "url": "https://github.com/Annosz/UIInfoSuite2/releases/download/v2.3.3/UIInfoSuite2.2.3.3.zip",
        "md5": "97d8c3bc38d6bd8b6cac31c6da034fd9",
        "fileSize": 586703,
        "updatePolicy": "exact",
        "tag": "3O4JywWMCD"
      },
      "details": {
        "category": "",
        "type": ""
      },
      "phase": 1
    },
```

**Comment by erri120** [comment]
Another one:

```json
"source": {
        "type": "bundle",
        "fileSize": 8192,
        "updatePolicy": "exact",
        "fileExpression": "Bundled - (Compat) DaisyNiko's Earthy Interface Compatibility - EventLookup.zip (v1.0.0)",
        "tag": "FPMWDESpMs"
      },
```
