### ISSUE TITLE
Nullexception in `OAuth2MessageFactory` for cached token

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2031]
Ive experienced a few times now that when downloading a collection it does not download all of the mods associated with the collection. 

Has anyone else experienced this?

**Comment by erri120** [comment]
Need logs, this is too vague.

**Comment by LukeNexusMods** [comment]
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/16978323/nexusmods.app.main.current.log)

**Comment by erri120** [comment]
I saw this exception as well, might be a concurrency issue.

```
00:16:17.162 [ERROR] (NexusMods.SingleProcess.CommandLineConfigurator) Exception while running handler NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler for `nxm://cyberpunk2077/collections/iszwwe/revisions/469`|System.InvalidOperationException: Nullable object must have a value.
   at NexusMods.Networking.NexusWebApi.Auth.OAuth2MessageFactory.GetOrRefreshToken(CancellationToken cancellationToken) in /_/src/Networking/NexusMods.Networking.NexusWebApi/Auth/OAuth2MessageFactory.cs:line 49
   at NexusMods.Networking.NexusWebApi.Auth.OAuth2MessageFactory.Create(HttpMethod method, Uri uri) in /_/src/Networking/NexusMods.Networking.NexusWebApi/Auth/OAuth2MessageFactory.cs:line 73
   at NexusMods.Networking.NexusWebApi.NexusApiClient.ModInfoAsync(String domain, ModId modId, CancellationToken token) in /_/src/Networking/NexusMods.Networking.NexusWebApi/NexusApiClient.cs:line 186
   at NexusMods.Networking.NexusWebApi.NexusModsLibrary.GetOrAddModPage(ModId modId, GameDomain gameDomain, CancellationToken cancellationToken) in /_/src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.cs:line 46
   at NexusMods.Networking.NexusWebApi.NexusModsLibrary.CreateDownloadJob(AbsolutePath destination, GameDomain gameDomain, ModId modId, FileId fileId, Optional`1 nxmData, CancellationToken cancellationToken) in /_/src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.cs:line 216
   at NexusMods.Collections.InstallCollectionJob.EnsureNexusModDownloaded(Mod mod) in /_/src/NexusMods.Collections/InstallCollectionJob.cs:line 218
   at NexusMods.Collections.InstallCollectionJob.EnsureNexusModDownloaded(Mod mod) in /_/src/NexusMods.Collections/InstallCollectionJob.cs:line 222
   at NexusMods.Collections.InstallCollectionJob.EnsureDownloaded(Mod mod) in /_/src/NexusMods.Collections/InstallCollectionJob.cs:line 199
   at NexusMods.Collections.InstallCollectionJob.<>c__DisplayClass33_0.<<StartAsync>b__1>d.MoveNext() in /_/src/NexusMods.Collections/InstallCollectionJob.cs:line 80
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at NexusMods.Collections.InstallCollectionJob.StartAsync(IJobContext`1 context) in /_/src/NexusMods.Collections/InstallCollectionJob.cs:line 80
   at NexusMods.Jobs.JobContext`2.Start() in /_/src/NexusMods.Jobs/JobContext.cs:line 43
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.HandleCollectionUrl(NXMCollectionUrl collectionUrl) in /_/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 120
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.HandleCollectionUrl(NXMCollectionUrl collectionUrl) in /_/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 120
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.Handle(String url, CancellationToken cancel) in /_/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 82
   at NexusMods.SingleProcess.CommandLineConfigurator.RunLink(String[] args, CancellationToken cancellationToken) in /_/src/NexusMods.SingleProcess/CommandLineConfigurator.cs:line 119

```
