### ISSUE TITLE
Spike / Bug: Some `update-desktop-database` binaries might not have a `--version` switch

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#2093]
# Bug Report

## Summary

In some distros it may be possible that the version of  `update-desktop-database`  shipped does not have a `--version` flag in the CLI.

[A User on Steam Deck](https://discord.com/channels/1134149061080002713/1134149062589960215/1288734365869670412) is experiencing an error in log for `update-desktop-database` on every boot with the following contents:

```
00:00:02.257 [ERROR] (NexusMods.CrossPlatform.Process.RuntimeDependencyChecker) update-desktop-database: exception while querying information|CliWrap.Exceptions.CommandExecutionException: Command execution failed because the underlying process (update-desktop-database#40434) returned a non-zero exit code (1).

Command:
update-desktop-database --version

You can suppress this validation by calling `WithValidation(CommandResultValidation.None)` on the command.
   at CliWrap.Command.ExecuteAsync(ProcessEx process, CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Command.Execution.cs:line 271
   at CliWrap.Command.ExecuteAsync(ProcessEx process, CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Command.Execution.cs:line 287
   at CliWrap.Command.ExecuteAsync(ProcessEx process, CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Command.Execution.cs:line 287
   at CliWrap.Command.ExecuteAsync(ProcessEx process, CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Command.Execution.cs:line 287
   at NexusMods.CrossPlatform.Process.ProcessFactory.ExecuteAsync(Command command, CancellationToken cancellationToken) in /_/src/NexusMods.CrossPlatform/Process/ProcessFactory.cs:line 118
   at NexusMods.CrossPlatform.Process.ProcessFactory.ExecuteAsync(Command command, Boolean logProcessOutput, CancellationToken cancellationToken) in /_/src/NexusMods.CrossPlatform/Process/ProcessFactory.cs:line 98
   at NexusMods.CrossPlatform.Process.ProcessFactory.ExecuteAsync(Command command, Boolean logProcessOutput, CancellationToken cancellationToken) in /_/src/NexusMods.CrossPlatform/Process/ProcessFactory.cs:line 101
   at NexusMods.CrossPlatform.Process.ProcessFactory.ExecuteAsync(Command command, Boolean logProcessOutput, CancellationToken cancellationToken) in /_/src/NexusMods.CrossPlatform/Process/ProcessFactory.cs:line 101
   at NexusMods.CrossPlatform.Process.ExecutableRuntimeDependency.QueryInstallationInformationImpl(CancellationToken cancellationToken) in /_/src/NexusMods.CrossPlatform/Process/ExecutableRuntimeDependency.cs:line 56
   at NexusMods.CrossPlatform.Process.RuntimeDependencyChecker.StartAsync(CancellationToken cancellationToken) in /_/src/NexusMods.CrossPlatform/Process/RuntimeDependencyChecker.cs:line 27
 ```

And their process stdout is:

```
Unknown option --version
Run "update-desktop-database --help" to see a full list of available command line options.
```

## Other information

[Chat from Discord](https://discord.com/channels/1134149061080002713/1134149062589960215/1288734365869670412).

This is relatively low priority; it's not breaking, but it pollutes logs. Users and devs may get wrong impressions if there are errors related to URL handlers.

**Comment by Sewer56** [comment]
> Do you know what OS the user had installed? 

SteamOS. As mentioned, they're running on Deck. The top of their logs was saying SteamOS.
