### ISSUE TITLE
Linux - Error when launching v0.6.3 AppImage

### ISSUE THREAD

**Issue by HalibutGitWiz** [Nexus-Mods/NexusMods.App#2234]
# Bug Report

## Summary

Launching v0.6.3 AppImage on EndeavourOS / XFCE crashes, while earlier versions worked fine on the same computer.

## Steps to reproduce

1. Follow [manual uninstall procedure](https://nexus-mods.github.io/NexusMods.App/users/Uninstall/#manual-uninstall-on-linux)
1. Download AppImage v0.6.3 and make it executable
1. Run `./NexusMods.App.x86_64.AppImage &`

## What is the expected behaviour?

Nexus Mods app starts

## Other information

Terminal output

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Invalid argument: GlobalCompare: does not match existing comparator leveldb.BytewiseComparator)
 ---> RocksDbSharp.RocksDbException: Invalid argument: GlobalCompare: does not match existing comparator leveldb.BytewiseComparator
   at RocksDbSharp.Native.rocksdb_open(IntPtr options, IntPtr name)
   at RocksDbSharp.RocksDb.Open(OptionsHandle options, String path)
   at NexusMods.MnemonicDB.Storage.RocksDbBackend.Backend.Init(AbsolutePath location)
   at NexusMods.MnemonicDB.Storage.DatomStore..ctor(ILogger`1 logger, DatomStoreSettings settings, IStoreBackend backend, TimeProvider timeProvider, Boolean bootstrap)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at NexusMods.DataModel.Services.<>c.<AddDataModel>b__0_2(IServiceProvider s) in /_/src/NexusMods.DataModel/Services.cs:line 92
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
   at NexusMods.App.Program.Main(String[] args) in /_/src/NexusMods.App/Program.cs:line 63

[1]  + IOT instruction (core dumped)  ./NexusMods.App.x86_64.AppImage
```

**Comment by mthorbruegge** [comment]
I run into the same problem on Stem Deck, same error message. Same error occurs with all versions since (including) 0.6.0. Version 0.5.3 still starts normally.

**Comment by SpiceOctopus** [comment]
Same for me on Fedora 41 KDE.

**Comment by PickMeNow** [comment]
Same issue here ArchLinux GNOME 47  6.11.6-zen1-1-zen.
Also tried the x64 linux tar.gz, same issue

**Comment by PoorPocketsMcNewHold** [comment]
Fedora 40 with the same issue. The Linux build seems borked.

**Comment by erri120** [comment]
You need to uninstall your previous version. See the FAQ: https://nexus-mods.github.io/NexusMods.App/users/faq/#why-do-i-have-to-uninstall-everything-to-update-the-app

**Comment by HalibutGitWiz** [comment]
> ## Steps to reproduce
> 
> **1. Follow [manual uninstall procedure](https://nexus-mods.github.io/NexusMods.App/users/Uninstall/#manual-uninstall-on-linux)**
> 1. Download AppImage v0.6.3 and make it executable
> 1. Run `./NexusMods.App.x86_64.AppImage &`

I deliberately stated this in my description so I don't get this kind of rude answer...

**Comment by erri120** [comment]
The exception thrown occurs when the app tries to load an existing database file of a previous version. You can check the log for the location of the database file and manually delete it, although it should be at the paths described in the docs.

**Comment by HalibutGitWiz** [comment]
I did the uninstall process again and it didn't change anything.
Then I did a full search on my whole system for files containing "nexus" and "mods" and found two outside of the paths specified in the uninstall procedure :

- /run/user/1000/NexusMods.App-sync_file.sync
- $HOME/.config/local/share/applications/com.nexusmods.app.desktop

Deleting those files fixed the issue.
