### ISSUE TITLE
Stardew Valley not detected on Linux Heroic

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#2401]
# Bug Report

## Summary
Stardew Valley (Linux version) is not detected through Heroic games store. 

## Steps to reproduce
1. Install the native SDV build via Heroic.
2. See it is not detected in the app. 

## What is the expected behaviour?
I can manage SDV

## Other information

[installed.json](https://github.com/user-attachments/files/18167992/installed.json)

[nexusmods.app.main.current.log](https://github.com/user-attachments/files/18168027/nexusmods.app.main.current.log)
[nexusmods.app.main.01.log](https://github.com/user-attachments/files/18168032/nexusmods.app.main.01.log)
[nexusmods.app.main.02.log](https://github.com/user-attachments/files/18168033/nexusmods.app.main.02.log)

**Comment by Pickysaurus** [comment]
A similar issue which is resulting in the Windows version not being found either [NexusModsTSVoid.zip](https://github.com/user-attachments/files/18168904/NexusModsTSVoid.zip)

**Comment by VoidSentient** [comment]
> A similar issue which is resulting in the Windows version not being found either [NexusModsTSVoid.zip](https://github.com/user-attachments/files/18168904/NexusModsTSVoid.zip)

Apologies, its working now. I didnt launch when I installed a couple days ago, I launched and tried opening the NexusMods launcher right after but Heroic (or however this game is detected) hadnt updated the files yet, I noticed it was detected about 20 minutes later.

**Comment by venohm69** [comment]
Having this issue as well.
Section from logs.
--------------------------------------------------------------------------
00:00:00.477 [ERROR] (NexusMods.StandardGameLocators.HeroicGogLocator) While looking for games: Unable to parse in /home/<USER NAME>/.config/heroic/gog_store/installed.json: `Installed { Platform = linux, Executable = , InstallPath = /home/<USER NAME>/Games/Heroic/Stardew Valley, InstallSize = 676.1 MiB, IsDlc = False, Version = 1.6.15.24357.8705766150, AppName = 1453375253, InstalledDLCs = System.Collections.Generic.List`1[System.Object], Language = en, VersionEtag = , BuildId = , PinnedVersion = False }`:
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at GameFinder.Launcher.Heroic.HeroicGOGHandler.Parse(Installed installed, AbsolutePath configPath, IFileSystem fileSystem)
   at GameFinder.Launcher.Heroic.HeroicGOGHandler.ParseInstalledJsonFile(AbsolutePath path, AbsolutePath configPath)+MoveNext()
--------------------------------------------------------------------------

Heroic installed.json file from ~/.config/heroic/gog_store/installed.json
--------------------------------------------------------------------------
File: installed.json
{
    "installed": [
        {
            "platform": "linux",
            "executable": "",
            "install_path": "/home/<USER NAME>/Games/Heroic/Stardew Valley",
            "install_size": "676.1 MiB",
            "is_dlc": false,
            "version": "1.6.15.24357.8705766150",
            "appName": "1453375253",
            "installedDLCs": [],
            "language": "en",
            "versionEtag": "",
            "buildId": "",
            "pinnedVersion": false
        }
    ]
}
--------------------------------------------------------------------------

**Comment by LukeNexusMods** [comment]
This is an important issue to fix.

**Comment by LukeNexusMods** [comment]
Thanks very much for raising a ticket with us and being involved in the app development process.

We have fixed the issue of Stardew Valley on Linux being detected. Due to current technical limitations when you unmanage the game it will remove some game files which means you will need to repair it or install it again. 

We understand this isn't ideal but we are working on a solution that means others wont get in the same position.

We recommend, unmanaging the game, repairing the install, closing the app, open it again and then manage the game again if you would like to continue modding with the Nexus Mods app.

If you need any further support or have any questions please let us know.
