### ISSUE TITLE
"Could not find analysis data for archive" exception on specific mods install

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#429]
# Bug Report

## Summary
At mod install (tested from CLI) of specific mods archives, the application crashes with the following exception:

```
Unhandled exception: System.InvalidOperationException: Could not find analysis data for archive
   at NexusMods.DataModel.ArchiveInstaller.AddMods(LoadoutId loadoutId, Hash archiveHash, String defaultModName, CancellationToken token) in C:\Dev\Repos\NexusMods.App\src\NexusMods.DataModel\ArchiveInstaller.cs:line 56
   at NexusMods.CLI.Verbs.InstallMod.<>c__DisplayClass6_0.<<Run>b__0>d.MoveNext() in C:\Dev\Repos\NexusMods.App\src\NexusMods.CLI\Verbs\InstallMod.cs:line 44
```

## Steps to reproduce
Clear the databases of the app to make sure that the archive isn't already indexed.
Run the install-mod command with one of the following files with which I was able to reproduce:
- LeanWolfs main file: https://www.nexusmods.com/skyrimspecialedition/mods/2017?tab=files
- XP32 Maximum skeleton main file: https://www.nexusmods.com/skyrimspecialedition/mods/1988?tab=files
The app will crash, but not with the above exception, rather it seems that the 7z process used to extract the archive crashed and that causes the app to crash in turn.

Following attempts to install the archive will trigger the exception above.

### Further details:
Debugging shows that on following attempts at installation of the same file, the failure seems to come from the fact that the application does have an entry in the database for the analysis data for the archive, but as an AnalyzedFile and not an AnalyzedArchive, presumably because file extraction failed on the first run, only leaving the initial file analysis data.

Interestingly they both happen to be Fomods, could be related or not.

**Comment by Al12rs** [comment]
Figured out the issue, apparently it's a 7z.exe bug with long output paths together with forward slashes:
https://sourceforge.net/p/sevenzip/discussion/45797/thread/a9a0f02618/

This works:
```
C:/Dev/Repos/NexusMods.App/src/NexusMods.App/bin/Release/net7.0/runtimes/win-x64/native/7z.exe x -bsp1 -y "-oG:\Documents\Downlaods\tempOut\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" "G:/Documents/Downlaods/XP32 Maximum Skeleton Special Extended-1988-4-81-1660739371.7z" -mmt=off
```
This works:
```
C:/Dev/Repos/NexusMods.App/src/NexusMods.App/bin/Release/net7.0/runtimes/win-x64/native/7z.exe x -bsp1 -y -o"G:/Documents/Downlaods/tempOut" "G:/Documents/Downlaods/XP32 Maximum Skeleton Special Extended-1988-4-81-1660739
371.7z" -mmt=off
```
This doesn't:
```
C:/Dev/Repos/NexusMods.App/src/NexusMods.App/bin/Release/net7.0/runtimes/win-x64/native/7z.exe x -bsp1 -y "-oG:/Documents/Downlaods/tempOut/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" "G:/Documents/Downlaods/XP32 Maximum Skeleton Special Extended-1988-4-81-1660739371.7z"A
```
