### ISSUE TITLE
Install fail due to Ini Analyzer exception if ini files contain comments

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#448]
Investigate exception:

```
Error analyzing C:/Users/Al12r/AppData/Local/Temp/NexusMods.App-7901cbff-1e8c-48f9-a2ef-7897aef75ecd/00cacd02-b1ff-441f-9bf9-a4b732c428f9/Character Creation/Randomizer/In Sync/meshes/actors/character/BodyGenData/XPMSE.esp/templates.ini with IniAnalzyer|IniParser.Exceptions.ParsingExcept
ion: Unknown file format. Couldn't parse the line: '#Arrow'. while parsing line number 0 with value '' - IniParser version: 2.5.2.0 while parsing line number 1 with value '#Arrow' - IniParser version: 2.5.2.0
 ---> IniParser.Exceptions.ParsingException: Unknown file format. Couldn't parse the line: '#Arrow'. while parsing line number 0 with value '' - IniParser version: 2.5.2.0
   at IniParser.Parser.IniDataParser.ProcessLine(String currentLine, IniData currentIniData)
   at IniParser.Parser.IniDataParser.Parse(String iniDataString)
   --- End of inner exception stack trace ---
   at IniParser.Parser.IniDataParser.Parse(String iniDataString)
   at IniParser.StreamIniDataParser.ReadData(StreamReader reader)
   at NexusMods.Games.Generic.FileAnalyzers.IniAnalzyer.AnalyzeAsync(FileAnalyzerInfo info, CancellationToken token)+MoveNext() in C:\Dev\Repos\NexusMods.App\src\Games\NexusMods.Games.Generic\FileAnalyzers\IniAnalzyer.cs:line 22
   at NexusMods.Games.Generic.FileAnalyzers.IniAnalzyer.AnalyzeAsync(FileAnalyzerInfo info, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at NexusMods.DataModel.ArchiveAnalyzer.AnalyzeFileInnerAsync(IStreamFactory sFn, CancellationToken token, Int32 level, Hash parent, Nullable`1 parentArchivePath, RelativePath parentPath, String fileName) in C:\Dev\Repos\NexusMods.App\src\NexusMods.DataModel\ArchiveAnalyzer.cs:line 193
   at NexusMods.DataModel.ArchiveAnalyzer.AnalyzeFileInnerAsync(IStreamFactory sFn, CancellationToken token, Int32 level, Hash parent, Nullable`1 parentArchivePath, RelativePath parentPath, String fileName) in C:\Dev\Repos\NexusMods.App\src\NexusMods.DataModel\ArchiveAnalyzer.cs:line 193
```

**Comment by Al12rs** [comment]
This also happens when trying to install ENB for SkyrimLE
http://enbdev.com/download_mod_tesskyrim.htm

**Comment by Al12rs** [comment]
This is triggering on many skyrim mods, I'm adding it to the next milestone
