### ISSUE TITLE
AdvancedHttpDownloader stuck, requesting a range of 0 bytes indefinitively.

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#483]
# Bug Report

## Summary

If you execute test `HttpDownloadTaskTests -> DownloadModFromUrl` using `Resources/RootedAtGameFolder/-Skyrim 202X 9.0 - Architecture-2347-9-0-1664994366.zip` as a parameter in commit c356d2b5b6c3212b572838079523dd0ce5b2b35b , the one of the following can happen:

- Either you get an exception from AdvancedHttpDownloader

<details>
  <summary>Stack Trace</summary>

```
System.Net.Http.HttpRequestException: Received an invalid status line: '0'.

System.Net.Http.HttpRequestException
Received an invalid status line: '0'.
   at System.Net.Http.HttpConnection.ParseStatusLine(ReadOnlySpan`1 line, HttpResponseMessage response)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NexusMods.Networking.HttpDownloader.AdvancedHttpDownloader.SendRangeRequest(ChunkState chunk, CancellationToken cancel) in /home/sewer/repos/NexusMods.App/src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs:line 306
   at NexusMods.Networking.HttpDownloader.AdvancedHttpDownloader.DownloadChunk(IJob`2 job, DownloadState download, ChunkState chunk, ChannelWriter`1 writes, CancellationToken cancel) in /home/sewer/repos/NexusMods.App/src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs:line 333
   at NexusMods.Networking.HttpDownloader.AdvancedHttpDownloader.<>c__DisplayClass14_0.<<DownloaderTask>b__0>d.MoveNext() in /home/sewer/repos/NexusMods.App/src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs:line 202
--- End of stack trace from previous location ---
   at NexusMods.Networking.HttpDownloader.AdvancedHttpDownloader.DownloaderTask(DownloadState state, ChannelWriter`1 writes, CancellationToken cancel) in /home/sewer/repos/NexusMods.App/src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs:line 194
   at NexusMods.Networking.HttpDownloader.AdvancedHttpDownloader.DownloadAsync(IReadOnlyList`1 sources, AbsolutePath destination, HttpDownloaderState downloaderState, Nullable`1 size, CancellationToken cancel) in /home/sewer/repos/NexusMods.App/src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs:line 104
   at NexusMods.Networking.Downloaders.Tasks.HttpDownloadTask.StartOrResumeDownload(TemporaryPath tempPath, CancellationToken token) in /home/sewer/repos/NexusMods.App/src/Networking/NexusMods.Networking.Downloaders/Tasks/HttpDownloadTask.cs:line 98
   at NexusMods.Networking.Downloaders.Tasks.HttpDownloadTask.ResumeImpl() in /home/sewer/repos/NexusMods.App/src/Networking/NexusMods.Networking.Downloaders/Tasks/HttpDownloadTask.cs:line 81
   at NexusMods.Networking.Downloaders.Tasks.HttpDownloadTask.StartImpl() in /home/sewer/repos/NexusMods.App/src/Networking/NexusMods.Networking.Downloaders/Tasks/HttpDownloadTask.cs:line 75
   at NexusMods.Networking.Downloaders.Tests.Tasks.HttpDownloadTaskTests.DownloadModFromUrl(String url) in /home/sewer/repos/NexusMods.App/tests/Networking/NexusMods.Networking.Downloaders.Tests/Tasks/HttpDownloadTaskTests.cs:line 39
   at Xunit.DependencyInjection.DependencyInjectionTestInvoker.AsyncStack(Task task, Activity activity)
```

</details>

or

- `LocalHttpServer` is stuck receiving a request with `bytes=52963-52963`.

The second case only seems to appear when there is a delay in receiving the responses from the server (in this case `LocalHttpServer`). You'll experience it if you either place something like `Thread.Sleep` or just hit a breakpoint in the server.

## Steps to reproduce

Execute test `HttpDownloadTaskTests -> DownloadModFromUrl` using `Resources/RootedAtGameFolder/-Skyrim 202X 9.0 - Architecture-2347-9-0-1664994366.zip` as a parameter in commit c356d2b5b6c3212b572838079523dd0ce5b2b35b . 

## Other information

Commit contains incomplete code, only pushed for purposes of providing a reproduction as this happened during work on a Work-In-Progress branch.

**Comment by halgari** [comment]
Yep, I'm actively trying to reproduce this locally, no luck yet

**Comment by Sewer56** [comment]
I forgot when exactly but I recall this being fixed, at least on my local machine.
Might have been in #484

**Comment by Sewer56** [comment]
Closing under the assumption that:
- https://github.com/Nexus-Mods/NexusMods.App/pull/484

Did indeed fix the issue, as it has not been reported since.
