### ISSUE TITLE
`PluginAnalyzer` tries to analyze non-Skyrim plugin files

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#526]
# Bug Report

## Summary
Open the App, login and select Skyrim as a game to manage.

The manage process (getting the game ready to mod/launch) takes a very long time (minutes).

## Steps to reproduce
1. Install the app from the executable.
2. Launch the app.
3. Login.
4. Manage Skyrim (Steam?)

## What is the expected behaviour?
The process to get the game into a state ready to mod needs to be faster, it seems to be taking around 90 seconds.

## Other information
```
00:03:44.161 [ERROR] Error analyzing C:/Program Files (x86)/Steam/steamapps/common/Skyrim Special Edition/Tools/zEdit_v0.6.6.1_-_Portable_x64/Oblivion.Hardcoded.dat with PluginAnalyzer|System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Mutagen.Bethesda.Plugins.Binary.Translations.RecordSpanExtensions.EnumerateSubrecords(ReadOnlyMemorySlice`1 span, GameConstants meta, Int32 offset)+MoveNext()
   at Mutagen.Bethesda.HeaderExt.Masters(ModHeaderFrame modHeader)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Mutagen.Bethesda.Plugins.Masters.MasterReferenceCollection.SetTo(IEnumerable`1 masters)
   at Mutagen.Bethesda.Plugins.Masters.MasterReferenceCollection.FromStream[TStream](TStream stream)
   at Mutagen.Bethesda.Plugins.Masters.MasterReferenceCollection.FromStream(Stream stream, ModKey modKey, GameRelease release, Boolean disposeStream)
   at Mutagen.Bethesda.Plugins.Binary.Streams.MutagenBinaryReadStream..ctor(Stream stream, ModKey modKey, GameRelease release, Int32 bufferSize, Boolean dispose, Int64 offsetReference)
   at Mutagen.Bethesda.Skyrim.SkyrimMod.CreateFromBinaryOverlay(Stream stream, SkyrimRelease release, ModKey modKey)
   at NexusMods.Games.BethesdaGameStudios.PluginAnalyzer.AnalyzeAsync(FileAnalyzerInfo info, CancellationToken ct)+MoveNext() in /_/src/Games/NexusMods.Games.BethesdaGameStudios/PluginAnalyzer.cs:line 21
   at NexusMods.DataModel.ArchiveAnalyzer.AnalyzeFileInnerAsync(IStreamFactory sFn, CancellationToken token, Int32 level, Hash parent, Nullable`1 parentArchivePath, RelativePath parentPath, String fileName) in /_/src/NexusMods.DataModel/ArchiveAnalyzer.cs:line 226
   at NexusMods.DataModel.ArchiveAnalyzer.AnalyzeFileInnerAsync(IStreamFactory sFn, CancellationToken token, Int32 level, Hash parent, Nullable`1 parentArchivePath, RelativePath parentPath, String fileName) in /_/src/NexusMods.DataModel/ArchiveAnalyzer.cs:line 226
00:05:14.591 [INFO] Loadout 19DD2B5D6C60C64F9534C383D2F89FB2 altered: Add game files
00:05:14.612 [INFO] Ready to show NexusMods.App.UI.LeftMenu.Items.IconView with autowired NexusMods.App.UI.LeftMenu.Items.IconViewModel.
```

**Comment by erri120** [comment]
From the log:

```
Error analyzing C:/Program Files (x86)/Steam/steamapps/common/Skyrim Special Edition/Tools/zEdit_v0.6.6.1_-_Portable_x64/Oblivion.Hardcoded.dat
```

This file was recognized as a `TES4` plugin file, and the `PluginAnalyzer` tried to open it using Mutagen. However, currently we always use the Skyrim SE binary overlay of Mutagen to read those files, which will fail if the plugin is for Oblivion.

We'd need to skip the analyze process if the plugin file isn't a Skyrim plugin file.

**Comment by Al12rs** [comment]
Regarding the long time, at first setup the App indexes and backups everything in the game folder, so if the game folder isn't completely vanilla it can take a very long time.

This is a problem. Ideally the app would know which are the "Vanilla" files and only index those, but the reality is that there is no way to have that information for all the different game installations that doesn't immediately break as soon as the game gets updated.

As a more feasible alternative, the Game extension would define glob patters that need to be indexed or patterns that need to be excluded (like .gitignore). Hopefully limiting indexing to only relevant stuff.

Still the problem remains that whatever the state of the game folder is when first the user tries to manage it, that is assumed to be the Vanilla state, even though it could be very far from it.
