### ISSUE TITLE
Loadout Synchronizer `RemovedFilesAreRemoved` is flaky

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#534]
See https://github.com/Nexus-Mods/NexusMods.App/actions/runs/5797158369?pr=532:

```
Expected (from mod in loadout.Mods.Valueswhere mod.Enabled == truefrom file in mod.Files.Valuesselect file).Count() to be 0, but found 2 (difference of 2).
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Numeric.NumericAssertions`2.Be(T expected, String because, Object[] becauseArgs)
   at NexusMods.DataModel.Tests.LoadoutSynchronizerTests.IngestChangesTest.RemovedFilesAreRemoved() in /home/runner/work/NexusMods.App/NexusMods.App/tests/NexusMods.DataModel.Tests/LoadoutSynchronizerTests/IngestChangesTest.cs:line 84
```

**Comment by halgari** [comment]
Haven't seen this in a long time now that we've been working on #486

**Comment by Al12rs** [comment]
I can still reproduce this occasionally locally

**Comment by Al12rs** [comment]
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/26797547/08fe3742-2cb7-4a67-af42-7cb131029198)

**Comment by halgari** [comment]
Fixed as part of the rework
