### ISSUE TITLE
Unhandled Exception when using AppImage.

### ISSUE THREAD

**Issue by PickMeNow** [Nexus-Mods/NexusMods.App#698]
# Bug Report

## Summary
Unhandled Exception when trying to open NexusMods.App.x86_64.AppImage

## Steps to reproduce
On console:
$ ./NexusMods.App.x86_64.AppImage

OS: 6.5.5-zen1-1-zen
DE: GNOME 44.5
WM: Mutter

## Additional Info:
Unhandled exception. System.IO.IOException: Read-only file system : '/tmp/.mount_NexusMTrleFJ/usr/bin/DataModel'
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at NexusMods.Paths.FileSystem.InternalCreateDirectory(AbsolutePath path)
   at NexusMods.Paths.BaseFileSystem.CreateDirectory(AbsolutePath path)
   at NexusMods.DataModel.DataModelSettings..ctor(AbsolutePath baseDirectory) in /_/src/NexusMods.DataModel/IDataModelSettings.cs:line 101
   at NexusMods.DataModel.DataModelSettings..ctor(IFileSystem s) in /_/src/NexusMods.DataModel/IDataModelSettings.cs:line 93
   at NexusMods.App.AppConfig..ctor() in /_/src/NexusMods.App/AppConfig.cs:line 19
   at NexusMods.App.Program.BuildHost() in /_/src/NexusMods.App/Program.cs:line 63
   at NexusMods.App.Program.Main(String[] args) in /_/src/NexusMods.App/Program.cs:line 27
   at NexusMods.App.Program.<Main>(String[] args)
Aborted (core dumped)

**Comment by Sewer56** [comment]
Can confirm this happens on 0.1 AppImage. 

I'll leave this open and check back in the future. For now, the non-AppImage version should work fine.

@halgari I take this is probably what you ran into when trying to execute on Deck

**Comment by Sewer56** [comment]
For more clarification:
- Running an `AppImage` mounts the binary in `/tmp`
- NMA stored DataModel in a subfolder of current working directory.
- The mount is read-only thus can't be written into.
- Even if you could hypothetically write into it, it's in `/tmp`, so would be wiped after a reboot.

Yeah. we'll probably want to be using XDG base directories.

**Comment by l0b0** [comment]
Also happens when running on Nix:

```console
❯ nix-build -A nexus-mods-app
❯ ./result/bin/NexusMods.App 
Unhandled exception. System.IO.IOException: Read-only file system : '/nix/store/nvhy88h449zv4g2cb62ww04n2q10ncly-nexus-mods-app-0.2.1/lib/nexus-mods-app/DataModel'
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at NexusMods.Paths.FileSystem.InternalCreateDirectory(AbsolutePath path)
   at NexusMods.Paths.BaseFileSystem.CreateDirectory(AbsolutePath path)
   at NexusMods.Paths.AbsolutePath.CreateDirectory()
   at NexusMods.DataModel.DataModelSettings..ctor(AbsolutePath baseDirectory) in /build/source/src/NexusMods.DataModel/IDataModelSettings.cs:line 101
   at NexusMods.DataModel.DataModelSettings..ctor(IFileSystem s) in /build/source/src/NexusMods.DataModel/IDataModelSettings.cs:line 93
   at NexusMods.App.AppConfig..ctor() in /build/source/src/NexusMods.App/AppConfig.cs:line 19
   at NexusMods.App.Program.BuildHost() in /build/source/src/NexusMods.App/Program.cs:line 72
   at NexusMods.App.Program.Main(String[] args) in /build/source/src/NexusMods.App/Program.cs:line 30
   at NexusMods.App.Program.<Main>(String[] args)
Aborted (core dumped)
```

**Comment by Sewer56** [comment]
This should be getting fixed, today or tomorrow 😉

**Comment by Sewer56** [comment]
![20231129_13h53m19s_grim](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/138ce4db-a4ab-4303-88b3-9812572ea090)

Delivered as promised.

I forgot I had a random a day off yesterday haha, so it came 2 days later instead. 
Anyway, this should be fixed with https://github.com/Nexus-Mods/NexusMods.App/pull/783

**Comment by l0b0** [comment]
@Sewer56 Still seems to crash when building with ad46fe757a046975189187a88dd73eb4dba98042:

```
❯ ./result/bin/NexusMods.App 
Unhandled exception. System.IO.IOException: Read-only file system : '/nix/store/5fd0qbglqa5j80fjlhiwyfp908f21v17-nexus-mods-app-0.2.2/lib/nexus-mods-app/DataModel'
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at NexusMods.Paths.FileSystem.InternalCreateDirectory(AbsolutePath path)
   at NexusMods.Paths.BaseFileSystem.CreateDirectory(AbsolutePath path)
   at NexusMods.Paths.AbsolutePath.CreateDirectory()
   at NexusMods.DataModel.DataModelSettings..ctor(AbsolutePath baseDirectory) in /build/source/src/NexusMods.DataModel/IDataModelSettings.cs:line 101
   at NexusMods.DataModel.DataModelSettings..ctor(IFileSystem s) in /build/source/src/NexusMods.DataModel/IDataModelSettings.cs:line 93
   at NexusMods.App.AppConfig..ctor() in /build/source/src/NexusMods.App/AppConfig.cs:line 19
   at NexusMods.App.Program.BuildHost() in /build/source/src/NexusMods.App/Program.cs:line 65
   at NexusMods.App.Program.Main(String[] args) in /build/source/src/NexusMods.App/Program.cs:line 32
   at NexusMods.App.Program.<Main>(String[] args)
Aborted (core dumped)
```

**Comment by Sewer56** [comment]
> @Sewer56 Still seems to crash when building with [ad46fe7](https://github.com/Nexus-Mods/NexusMods.App/commit/ad46fe757a046975189187a88dd73eb4dba98042):
> 
> ```
> ❯ ./result/bin/NexusMods.App 
> Unhandled exception. System.IO.IOException: Read-only file system : '/nix/store/5fd0qbglqa5j80fjlhiwyfp908f21v17-nexus-mods-app-0.2.2/lib/nexus-mods-app/DataModel'
>    at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
>    at System.IO.Directory.CreateDirectory(String path)
>    at NexusMods.Paths.FileSystem.InternalCreateDirectory(AbsolutePath path)
>    at NexusMods.Paths.BaseFileSystem.CreateDirectory(AbsolutePath path)
>    at NexusMods.Paths.AbsolutePath.CreateDirectory()
>    at NexusMods.DataModel.DataModelSettings..ctor(AbsolutePath baseDirectory) in /build/source/src/NexusMods.DataModel/IDataModelSettings.cs:line 101
>    at NexusMods.DataModel.DataModelSettings..ctor(IFileSystem s) in /build/source/src/NexusMods.DataModel/IDataModelSettings.cs:line 93
>    at NexusMods.App.AppConfig..ctor() in /build/source/src/NexusMods.App/AppConfig.cs:line 19
>    at NexusMods.App.Program.BuildHost() in /build/source/src/NexusMods.App/Program.cs:line 65
>    at NexusMods.App.Program.Main(String[] args) in /build/source/src/NexusMods.App/Program.cs:line 32
>    at NexusMods.App.Program.<Main>(String[] args)
> Aborted (core dumped)
> ```

I think you've built with the wrong commit, try building with 730e473272534aae68f57a1d5734a64738cece2c

The commit you've built with is the first commit in that branch, not the latest.

**Comment by l0b0** [comment]
> The commit you've built with is the first commit in that branch, not the latest.

:facepalm: Thank you! master builds; now it fails to run for a different reason:

```
❯ ./result/bin/NexusMods.App 
00:00:00.000 [DEBUG] Application starting in release mode
Unhandled exception. System.InvalidOperationException: No service for type 'NexusMods.Paths.IFileSystem' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at NexusMods.App.Services.<>c.<AddApp>b__1_1(IServiceProvider s) in /build/source/src/NexusMods.App/Services.cs:line 110
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at NexusMods.App.Program.Main(String[] args) in /build/source/src/NexusMods.App/Program.cs:line 62
   at NexusMods.App.Program.<Main>(String[] args)
Aborted (core dumped)
```
