### ISSUE TITLE
Exception when managing a new game (percentage out of range)

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#805]
Reproduced once when trying to mange a new game. App didn't crash but it stopped the indexing process.
Pressing the Manage button again worked fine.

Stack trace:
```
00:00:12.135 [ERROR] Unhandled exception|System.ArgumentException: Value does not fall within the expected range.
   at NexusMods.Abstractions.Values.Percent.CreateClamped(Double d) in /_/src/NexusMods.Abstractions/Values/Percent.cs:line 65
   at NexusMods.Common.AbsolutePathExtensions.<>c__DisplayClass0_0.<<XxHash64Async>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at NexusMods.Hashing.xxHash64.StreamExtensions.HashingCopyAsync(Stream inputStream, Stream outputStream, CancellationToken token, Func`2 reportFn)
   at NexusMods.Common.AbsolutePathExtensions.XxHash64Async(AbsolutePath input, IActivitySource`1 job, CancellationToken token) in /_/src/NexusMods.Common/AbsolutePathExtensions.cs:line 27
   at NexusMods.Common.AbsolutePathExtensions.XxHash64Async(AbsolutePath input, IActivitySource`1 job, CancellationToken token) in /_/src/NexusMods.Common/AbsolutePathExtensions.cs:line 27
   at NexusMods.DataModel.FileHashCache.<>c__DisplayClass6_0.<<IndexFoldersAsync>b__4>d.MoveNext() in /_/src/NexusMods.DataModel/FileHashCache.cs:line 126
--- End of stack trace from previous location ---
 at NexusMods.Common.ParallelExtensions.<>c__DisplayClass0_0`2.<<ParallelForEach>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
at NexusMods.Common.ParallelExtensions.ParallelForEach[TFrom,TTo](IEnumerable`1 source, Func`3 body) in /_/src/NexusMods.Common/ParallelExtensions.cs:line 18
   at NexusMods.DataModel.FileHashCache.IndexFoldersAsync(IEnumerable`1 paths, CancellationToken token)+MoveNext() in /_/src/NexusMods.DataModel/FileHashCache.cs:line 116
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at NexusMods.DataModel.FileHashCache.IndexDiskState(GameInstallation installation) in /_/src/NexusMods.DataModel/FileHashCache.cs:line 172
   at NexusMods.DataModel.LoadoutSynchronizer.ALoadoutSynchronizer.Manage(GameInstallation installation) in /_/src/NexusMods.DataModel/LoadoutSynchronizer/ALoadoutSynchronizer.cs:line 533
   at NexusMods.Games.BethesdaGameStudios.BethesdaLoadoutSynchronizer.Manage(GameInstallation installation) in /_/src/Games/NexusMods.Games.BethesdaGameStudios/BethesdaLoadoutSynchronizer.cs:line 16
   at NexusMods.DataModel.Loadouts.LoadoutRegistry.Manage(GameInstallation installation, String name) in /_/src/NexusMods.DataModel/Loadouts/LoadoutRegistry.cs:line 428
   at NexusMods.App.UI.RightContent.FoundGamesViewModel.ManageGame(GameInstallation installation) in /_/src/NexusMods.App.UI/RightContent/FoundGamesViewModel.cs:line 34
   at NexusMods.App.UI.RightContent.FoundGamesViewModel.<>c__DisplayClass9_0.<<InitializeFromFound>b__3>d.MoveNext() in /_/src/NexusMods.App.UI/RightContent/FoundGamesViewModel.cs:line 55
--- End of stack trace from previous location ---
   at NexusMods.App.UI.RightContent.FoundGamesViewModel.<>c__DisplayClass9_0.<<InitializeFromFound>b__2>d.MoveNext() in /_/src/NexusMods.App.UI/RightContent/FoundGamesViewModel.cs:line 55
   ```

**Comment by erri120** [comment]
Looking at the code and stacktrace, `Percent.CreateClamped` will throw if if the input value `d` is either NaN (not a number) or infinity:

https://github.com/Nexus-Mods/NexusMods.App/blob/79171ab5d1b686a836e6a63c0d02644b820450ed/src/NexusMods.Abstractions/Values/Percent.cs#L64-L65

The code that triggers this exception is a call to `IActivitySource<Size>.AddProgress` in `XxHash64Async`: https://github.com/Nexus-Mods/NexusMods.App/blob/79171ab5d1b686a836e6a63c0d02644b820450ed/src/NexusMods.Common/AbsolutePathExtensions.cs#L29

The implementation has a `IsNan` check already, so it's only possible that `d` is infinity:

https://github.com/Nexus-Mods/NexusMods.App/blob/79171ab5d1b686a836e6a63c0d02644b820450ed/src/NexusMods.DataModel/Activities/Activity.cs#L167-L184

I'm guessing that `var percent = value / _max.Value` is what produces that infinity value, since `_max` is the sum of all files being hashed:

https://github.com/Nexus-Mods/NexusMods.App/blob/899fd412775350ec0d671041996ad7892c4c5f57/src/NexusMods.DataModel/FileHashCache.cs#L114

**Comment by Al12rs** [comment]
Should be fixed
