### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#817]
https://github.com/Nexus-Mods/NexusMods.App/actions/runs/7209975163/job/19642115387

```
Error: 0.839 [ERROR] Failed to connect to main process|System.FormatException: Input string was not in a correct format. Failure to parse near offset 12. Expected an ASCII digit.
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(String format, Object[] args)
   at NexusMods.ProxyConsole.SpectreRenderer.ToSpectreAsync(IRenderable renderable)
   at NexusMods.ProxyConsole.SpectreRenderer.RenderAsync(IRenderable renderable)
   at NexusMods.ProxyConsole.ClientRendererAdaptor.ForwardCommands()
   at NexusMods.SingleProcess.ClientProcessDirector.RunTillCloseAsync(ConsoleSettings proxy)
   at NexusMods.SingleProcess.ClientProcessDirector.StartClientAsync(ConsoleSettings proxy)
   at NexusMods.SingleProcess.StartupDirector.SendCommandAsync(String[] args, IAnsiConsole console)
```

**Comment by erri120** [comment]
Closed as not relevant anymore.
