### ISSUE TITLE
Xunit runner crashes tests

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#873]
Tests have recently started failing randomly, however, it's not our actual tests but the test runner that has an issue. This stacktrace keeps popping up randomly at different places and at different times, but it's always the same trace with the same exception `System.ObjectDisposedException : Cannot access a disposed object.`.

```
2024-01-25T13:41:43.1100592Z [xUnit.net 00:00:01.09]   Finished:    NexusMods.Games.RedEngine.Tests
2024-01-25T13:41:43.1106609Z [xUnit.net 00:00:01.11]     [FATAL ERROR] System.ObjectDisposedException
2024-01-25T13:41:43.1110352Z [xUnit.net 00:00:01.11]       System.ObjectDisposedException : Cannot access a disposed object.
2024-01-25T13:41:43.1112061Z [xUnit.net 00:00:01.11]       Object name: 'Microsoft.Win32.SafeHandles.SafeWaitHandle'.
2024-01-25T13:41:43.1113025Z [xUnit.net 00:00:01.11]       Stack Trace:
2024-01-25T13:41:43.1114231Z [xUnit.net 00:00:01.11]            at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
2024-01-25T13:41:43.1115697Z [xUnit.net 00:00:01.11]            at Interop.Kernel32.SetEvent(SafeWaitHandle handle)
2024-01-25T13:41:43.1116839Z [xUnit.net 00:00:01.11]            at System.Threading.EventWaitHandle.Set()
2024-01-25T13:41:43.1119795Z [xUnit.net 00:00:01.11]         /_/src/xunit.runner.utility/Extensions/MessageSinkMessageExtensions.cs(39,0): at MessageSinkMessageExtensions.Dispatch[TMessage](IMessageSinkMessage message, HashSet`1 messageTypes, MessageHandler`1 callback)
```

**Comment by Al12rs** [comment]
We haven't seen this since the xUnit update, so closing
