### ISSUE TITLE
Zero exit code when "XOpenDisplay failed"

### ISSUE THREAD

**Issue by l0b0** [Nexus-Mods/NexusMods.App#958]
# Bug Report

## Summary

When trying to run a [non-interactive test without access to the desktop](https://github.com/l0b0/nixpkgs/blob/02b90decd94ef0c23d3816c906f71e4418302cbb/pkgs/by-name/ne/nexus-mods-app/package.nix#L59-L59), there's a fatal error, but the exit code is zero.

## Steps to reproduce

1. Check out https://github.com/NixOS/nixpkgs/pull/270372
2. Run `nix-build --attr pkgs.nexus-mods-app.passthru.tests.serve`

## What is the expected behaviour?

If the application cannot start the exit code should be non-zero (and ideally unique per common failure case).

## Other information

Log:

```
❯ nix-build --attr pkgs.nexus-mods-app.passthru.tests.serve
checking outputs of '/nix/store/zapcmacp12g1h0lvnrz6vix186s2yzqb-nexus-mods-app-test-serve.drv'...
00:00:00.000 [DEBUG] Application starting in release mode
00:00:00.013 [DEBUG] Calling startup handler
00:00:00.015 [INFO] Starting application with args: 
00:00:00.016 [INFO] Starting main process from client process: 5
00:00:00.020 [DEBUG] Starting main process
00:00:00.020 [INFO] Starting main process /nix/store/3bx00filk7463ng8bd9c9ihkpjpixkpf-nexus-mods-app-0.3/lib/nexus-mods-app/NexusMods.App with arguments: main-process
00:00:00.022 [DEBUG] Main process started with PID: 21
00:00:00.000 [DEBUG] Application starting in release mode
00:00:00.027 [DEBUG] Calling startup handler
00:00:00.029 [INFO] Starting application with args: main-process
00:00:00.031 [INFO] Main using SyncFile: /build/NexusMods.App-single_process.sync
00:00:00.034 [INFO] No main process found, starting main process (21)
00:00:00.037 [INFO] Started TCP listener on port 37791
00:00:00.038 [INFO] This process (21) is now the main process
00:00:00.352 [INFO] Found main process 21 listening on port 37791
00:00:00.048 [INFO] Accepted TCP connection from 45876
00:00:00.358 [DEBUG] Connected to main process 21 on port 37791
00:00:00.118 [DEBUG] Starting UI window
00:00:00.121 [DEBUG] Using sqlite data store at .local/share/NexusMods.App/DataModel/DataModel.sqlite
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
00:00:00.316 [FATAL] Exception crashed the application!|System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.AvaloniaX11PlatformExtensions.<>c.<UseX11>b__0_0()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at NexusMods.App.Startup.Main(IServiceProvider provider, String[] args) in /build/source/src/NexusMods.App/Startup.cs:line 26
00:00:00.634 [DEBUG] Startup handler returned 0
/nix/store/5gbp42nhci2gb1ias5x6jxfg8agnbw2b-nexus-mods-app-test-serve
```

**Comment by Sewer56** [comment]
I suspect this is probably caused by design of https://github.com/Nexus-Mods/NexusMods.SingleProcessApp

Related issue:
- https://github.com/Nexus-Mods/NexusMods.SingleProcessApp/issues/7

In NMA, the starting process becomes an idle process, and it actually forks itself to create the UI process.Then the original process just idles there.

Because the error is thrown inside the forked process, it doesn't percolate (travel) back to the original process. After a while, the original process dies, because it has no peers (UI instances), and therefore 'exits successfully'.

----------

Note: I didn't debug this (yet), but I believe this is probably what's happening under the hood.
