### ISSUE TITLE
Win32Exception when clicking "log in" button

### ISSUE THREAD

**Issue by l0b0** [Nexus-Mods/NexusMods.App#960]
# Bug Report

## Summary

After encountering #959 and clicking the log in button nothing happens in the GUI.

## Steps to reproduce

1. Check out https://github.com/NixOS/nixpkgs/pull/270372
2. Run `nix-build --attr pkgs.nexus-mods-app`
3. Run `./result/bin/NexusMods.App`
4. Dismiss the diagnostics and usage data sharing dialogue
5. Click the "log in" button

## What is the expected behaviour?

A login dialogue should appear, or something like that.

## Other information

Log:

```console
00:00:16.994 [ERROR] Unhandled exception|System.ComponentModel.Win32Exception (2): Failed to start a process with file path 'update-desktop-database'. Target file or working directory doesn't exist, or the provided credentials are invalid. ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'update-desktop-database' with working directory '/home/username/my projects/nixpkgs'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 56
   at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 68
   at CliWrap.Command.ExecuteAsync(CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Command.Execution.cs:line 307
   at CliWrap.Command.ExecuteAsync(CancellationToken cancellationToken) in /_/CliWrap/Command.Execution.cs:line 326
   at NexusMods.CrossPlatform.Process.ProcessFactory.ExecuteAsync(Command command, CancellationToken cancellationToken) in /build/source/src/NexusMods.CrossPlatform/Process/ProcessFactory.cs:line 14
   at NexusMods.CrossPlatform.ProtocolRegistration.ProtocolRegistrationLinux.Register(String protocol, String friendlyName, String workingDirectory, String commandLine) in /build/source/src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs:line 68
   at NexusMods.CrossPlatform.ProtocolRegistration.ProtocolRegistrationLinux.RegisterSelf(String protocol) in /build/source/src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs:line 36
   at NexusMods.Networking.NexusWebApi.LoginManager.LoginAsync(CancellationToken token) in /build/source/src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs:line 103
   at NexusMods.App.UI.Controls.TopBar.TopBarViewModel.Login() in /build/source/src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs:line 73
```

I'm not sure where the `update-desktop-database` command is supposed to come from. It seems to be mentioned in only one place in the project, [where it's being run](https://github.com/l0b0/NexusMods.App/blob/63b31f32f7b73dec7c285ba5478fcdea52d14cbe/src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs#L65-L65).

**Comment by Sewer56** [comment]
I've never used Nix myself, but some quick googling around, I believe the equivalent commandline on Nix might be: `nix-shell -p desktop_file_utils --run "update-desktop-database -v ~/.local/share/applications"`

**Comment by l0b0** [comment]
Yeah, I think I need to make `update-desktop-database` available on `$PATH` at runtime. Will close if that turns out to be the issue.

**Comment by erri120** [comment]
We should add this to the docs and mention that we require the desktop file utils package.
